name: 'distribution'
on: push
jobs:
  test:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install Dependencies and Build
        working-directory: src/main/frontend
        run: |
          yarn install
          yarn build