name: 'distribution'
on: push
jobs:
  test:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Install Yarn
        run: yarn install
      - name: Build Specific Subfolder
        run: |
          cd src/main/frontend
          yarn build
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=src/main/frontend --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}