name: 'distribution'
on: push
jobs:
  test:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Install Yarn
        run: yarn install
      - name: Build Specific Subfolder
        run: |
          cd src/main/frontend
          yarn build